// MercadoPago Module Options
export const MERCADOPAGO_OPTIONS_PROVIDER = Symbol('MERCADOPAGO_OPTIONS_PROVIDER');

// MercadoPago Service Options
export const MERCADOPAGO_CONFIG_PROVIDER = Symbol('MERCADOPAGO_CLIENT_CONFIG_PROVIDER');
export const MERCADOPAGO_PAYMENT_PROVIDER = Symbol('MERCADOPAGO_PAYMENT_PROVIDE');
export const MERCADOPAGO_SUBSCRIPTION_PROVIDER = Symbol('MERCADOPAGO_SUBSCRIPTION_PROVIVDER');
export const MERCADOPAGO_PREFERENCE_PROVIDER = Symbol('MERCADOPAGO_PREFERENCE_PROVIDER');
